version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - DBHOST=db
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - db
    entrypoint: go run main.go
    restart: always
  db:
    image: postgres:14.7-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
